minor update
fix in update_telegram.sh
update psql-file

diff --git a/psql-file b/psql-file
--- a/psql-file
+++ b/psql-file
@@ -21,11 +21,11 @@ grep -v '^#' $DIR_LIST_FILE | while read -r PTH ; do
 		if [ -n "$ARGUMENTS" ]; then
 			ARGUMENTS="-v $ARGUMENTS"
 		fi
-		psql -f $FILE_FULL_PATH $ARGUMENTS		
+		psql --pset="footer=off" --pset="border=2" --pset="format=wrapped" -f $FILE_FULL_PATH $ARGUMENTS		
 		exit 2
 	fi
 done
 
 [[ $? == 2 ]] && exit 0
->&2 echo "Sql file not found"
+	>&2 echo "Sql file not found"
 exit 1
