Revert "type changed for all files"
This reverts commit 9f7f8fe735f749ce668ebbc1d56391cdb00d478a.

diff --git a/psql-file b/psql-file
--- a/psql-file
+++ b/psql-file
@@ -1,1 +1,31 @@
-/home/schumi/bin/db/psql-file
+#!/bin/bash
+
+SQL_FILE_NAME=$1;
+if [ -z "$SQL_FILE_NAME" ]; then
+	>&2 echo "Missing argument SQL_FILE_NAME"
+	exit 1
+fi
+
+DIR_LIST_FILE=$(basename "$0"); DIR_LIST_FILE="${DIR_LIST_FILE%.*}"; DIR_LIST_FILE=$(dirname "$0")/$DIR_LIST_FILE.list
+if [ ! -f $DIR_LIST_FILE ]; then
+	>&2 echo "Missing file $(basename "$DIR_LIST_FILE")"
+	exit 1
+fi
+
+shift 1
+ARGUMENTS="$@"
+
+grep -v '^#' $DIR_LIST_FILE | while read -r PTH ; do
+	FILE_FULL_PATH=$(find $PTH -name $SQL_FILE_NAME)    
+	if [ -n "$FILE_FULL_PATH" ]; then
+		if [ -n "$ARGUMENTS" ]; then
+			ARGUMENTS="-v $ARGUMENTS"
+		fi
+		psql --pset="footer=off" --pset="border=2" --pset="format=wrapped" -f $FILE_FULL_PATH $ARGUMENTS		
+		exit 2
+	fi
+done
+
+[[ $? == 2 ]] && exit 0
+	>&2 echo "Sql file not found"
+exit 1
